export const SIGNUP_REQUEST = `SIGNUP_REQUEST`;
export const SIGNUP_SUCCESS = `SIGNUP_SUCCESS`;
export const SIGNUP_FAILURE = `SIGNUP_FAILURE`;
export const SIGNUP_RESET = `SIGNUP_RESET`;

export const LOGIN_REQUEST = `LOGIN_REQUEST`;
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;
export const LOGIN_FAILURE = `LOGIN_FAILURE`;
export const LOGIN_RESET = `LOGIN_RESET`;
export const SET_CURRENT_USER = `SET_CURRENT_USER`;

export const LOGOUT_REQUEST = `LOGOUT_REQUEST`;
export const LOGOUT_SUCCESS = `LOGOUT_SUCCESS`;

export const MESSAGES_REQUEST = `MESSAGES_REQUEST`;
export const MESSAGEs_SUCCESS = `MESSAGES_SUCCESS`;
export const MESSAGES_FAILURE = `MESSAGES_FAILURE`;
export const SET_SELECTED_MESSAGE = `SET_SELECTED_MESSAGE`;
export const RESET_SELECTED_MESSAGE = `RESET_SELECTED_MESSAGE`;
export const DELETE_MESSAGE = `DELETE_MESSAGE`;